import { TarghettiError } from "../src/modules/targhetti/targhetti.locale";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import * as XLSX from "xlsx";
import { createEventBus, type EventTransport } from "../src/core/events/eventBus";
import { asRecord, equipmentGroups, labelRows, manualConnection, normalizeMark, positionChanges, projectEndpoints, validateCatalogue } from "../src/modules/targhetti/targhetti.logic";
import type { TarghettiEvent } from "../src/modules/targhetti/targhetti.types";
import type { CoreEvent } from "../src/features/core-command/types";
import { buildLabelWorkbook } from "../src/modules/targhetti/targhetti.export";

const source = process.argv[2];
if (!source) throw new Error("Chemin du catalogue requis.");
const catalogue = validateCatalogue(JSON.parse(readFileSync(source, "utf8")));
const owner = "test-owner";
const makeEvent = (id: string, type: string, payload: Record<string, unknown>, status = "validated", validatedBy = owner): TarghettiEvent => ({ id, event_type: type, validation_status: status, created_at: `2026-10-06T12:00:${id.padStart(2,"0")}Z`, validated_at: `2026-10-06T12:00:${id.padStart(2,"0")}Z`, validated_by: validatedBy, payload: { owner_id: owner, catalogueId: catalogue.id, ...payload } });
assert.equal(catalogue.pages.length, 56);
assert.equal(catalogue.endpoints.length, 4076);
assert.equal(new Set(catalogue.endpoints.map(e=>e.sourceRow)).size, 2038);
assert.equal(new Set(catalogue.endpoints.map(e=>e.equipmentCode)).size, 878);
assert(catalogue.endpoints.every(e=>Object.keys(e.details).length===95));
assert.equal(normalizeMark("1-6 C RC001"), "1-6CRC001");
assert.notEqual(normalizeMark("1-6 C RC001"),normalizeMark("C RC001"));
assert.notEqual(normalizeMark("I RS 0*1"),normalizeMark("I RS 001"));
const prepared=projectEndpoints(catalogue,[],owner);
assert.equal(prepared.length,3752);
assert.equal(new Set(prepared.map(e=>e.sourceRow)).size,1876);
assert.equal(equipmentGroups(prepared).length,870);
assert(prepared.every(e=>!e.cableMark.includes("*")));
assert.equal(catalogue.endpoints.filter(e=>e.cableMark.includes("*")).length,324);
// A generated XLSX must remove entire starred rows, including star-only equipment.
const star={...prepared[0],id:"star-fixture",cableMark:"C * TEST",equipmentCode:"STAR_ONLY",confirmedPosition:null};
const printable={...prepared[0],confirmedPosition:"J2"};
assert.deepEqual(labelRows([star,printable],"both"),{metal:[printable.cableMark],internal:[`${printable.cableMark} - J2`]});
assert.throws(()=>labelRows([star],"metal"),TarghettiError);
assert.deepEqual(positionChanges([star],{[star.id]:"J9"},3),[]);
assert.equal(equipmentGroups([star]).length,0);
const allBook=buildLabelWorkbook([...prepared,star],"metal",XLSX).workbook;
const roundTrip=XLSX.read(XLSX.write(allBook,{type:"buffer",bookType:"xlsx"}),{type:"buffer"});
assert.equal(roundTrip.SheetNames.length,870);
const allLabels=roundTrip.SheetNames.flatMap(name=>XLSX.utils.sheet_to_json<string[]>(roundTrip.Sheets[name],{header:1})).map(row=>row[0]);
assert.equal(allLabels.length,3752);
assert.deepEqual([...allLabels].sort(),prepared.map(e=>e.cableMark).sort());
assert(allLabels.every(mark=>!mark.includes("*")));
const rcp = catalogue.endpoints.filter(e=>e.equipmentCode === "411005010001");
assert.equal(rcp.length,7);
assert(labelRows(projectEndpoints(catalogue,[],owner).filter(e=>e.equipmentCode === "411005010001"),"metal").metal.includes("1-6 C RC001"));
const cable = rcp.find(e=>e.cableMark === "C RC 002")!;
assert.equal(cable.candidates.length,1);assert.equal(cable.candidates[0].position,"J2");assert.equal(cable.candidates[0].page,3);
const opposite = catalogue.endpoints.find(e=>e.cableMark === "C RC 002" && e.equipmentCode !== cable.equipmentCode)!;
assert(opposite);assert(opposite.candidates.every(c=>c.position !== "J2"));
const change = { endpointId: cable.id, position: "J2", page:3 };
for (const ignored of [makeEvent("01","targhetti.positions",{changes:[change]},"pending"),makeEvent("02","targhetti.positions",{changes:[change]},"rejected"),makeEvent("03","targhetti.positions",{changes:[change]},"validated","other"),makeEvent("04","targhetti.positions",{changes:[change],owner_id:"other"}),makeEvent("05","targhetti.positions",{changes:[change],catalogueId:"old-revision"})]) assert.equal(projectEndpoints(catalogue,[ignored],owner).find(e=>e.id===cable.id)!.confirmedPosition,null);
const valid = makeEvent("06","targhetti.positions",{changes:[change]});
let rows=projectEndpoints(catalogue,[valid],owner), local=rows.find(e=>e.id===cable.id)!;
assert.equal(labelRows([local],"both").metal[0],"C RC 002");assert.equal(labelRows([local],"both").internal[0],"C RC 002 - J2");
const pair=buildLabelWorkbook([star,local],"both",XLSX).workbook;
assert.deepEqual(pair.SheetNames,["411005010001_MET","411005010001_INT"]);
assert.deepEqual(XLSX.utils.sheet_to_json(pair.Sheets[pair.SheetNames[0]],{header:1}),[["C RC 002"]]);
assert.deepEqual(XLSX.utils.sheet_to_json(pair.Sheets[pair.SheetNames[1]],{header:1}),[["C RC 002 - J2"]]);
assert.equal(rows.find(e=>e.id===opposite.id)!.confirmedPosition,null);
const unknown = rows.find(e=>e.id===opposite.id)!;
assert.throws(()=>buildLabelWorkbook([unknown],"internal",XLSX),TarghettiError);
assert.throws(()=>labelRows([local,unknown],"both"),TarghettiError);
const fakeTbdPrinted = makeEvent("22","targhetti.printed",{labels:[{endpointId:unknown.id,cableMark:unknown.cableMark,position:"TBD",kind:"internal"}]});
assert(!projectEndpoints(catalogue,[fakeTbdPrinted],owner).find(e=>e.id===unknown.id)!.printedInternal);
assert.equal(unknown.confirmedPosition,null);
const sourceTbd = {...unknown,confirmedPosition:"TBD"};
assert.deepEqual(labelRows([sourceTbd],"internal").internal,["C RC 002 - TBD"]);
assert.equal(labelRows([rows.find(e=>e.id===opposite.id)!],"metal").metal[0],"C RC 002");
const printed=makeEvent("07","targhetti.printed",{labels:[{endpointId:cable.id,cableMark:cable.cableMark,position:"J2",kind:"internal"},{endpointId:cable.id,cableMark:cable.cableMark,kind:"metal"}]});
local=projectEndpoints(catalogue,[printed,valid],owner).find(e=>e.id===cable.id)!;assert(local.printedInternal);assert(local.printedMetal);
const revised=makeEvent("08","targhetti.positions",{changes:[{...change,position:"J5"}]});
const stale=makeEvent("09","targhetti.printed",{labels:[{endpointId:cable.id,cableMark:cable.cableMark,position:"J2",kind:"internal"}]});
local=projectEndpoints(catalogue,[stale,revised,valid,printed],owner).find(e=>e.id===cable.id)!;assert.equal(local.confirmedPosition,"J5");assert(!local.printedInternal);assert(local.printedMetal);
const drafted=positionChanges([local],{[local.id]:"PP3 J1-J2"},42);assert.equal(drafted[0].position,"PP3 J1-J2");assert.equal(drafted[0].page,42);
const unconfirmed=projectEndpoints(catalogue,[],owner).find(e=>e.id===cable.id)!;
assert.equal(positionChanges([unconfirmed],{[cable.id]:"J99"},42)[0].page,42);
assert.throws(()=>validateCatalogue({...catalogue,pages:[]}),TarghettiError);
assert.throws(()=>validateCatalogue({...catalogue,endpoints:[{...cable,details:{bad:[]}}]}),TarghettiError);
assert.throws(()=>validateCatalogue({...catalogue,endpoints:[cable,cable]}),TarghettiError);
assert.throws(()=>validateCatalogue({...catalogue,id:"../escape"}),TarghettiError);
const input={cableMark:"PDF TEST 001",cableType:"CAT7",page:42,fromCode:"461.001.010.001",toCode:"411005010001",fromLocal:"TEST",toLocal:"TEST2",fromPosition:"PP3 J1-J2",toPosition:"J15"};
const addition=manualConnection(catalogue,rows,input,"fixture");
assert.equal(addition.endpoints.length,2);assert.equal(addition.endpoints[0].equipmentCode,"461001010001");
assert.throws(()=>manualConnection(catalogue,rows,{...input,cableMark:cable.cableMark},"duplicate"),TarghettiError);
assert.throws(()=>manualConnection(catalogue,rows,{...input,cableMark:"PDF TEST * 001"},"star"),TarghettiError);
assert.equal(projectEndpoints(catalogue,[makeEvent("10","targhetti.endpoints",addition,"pending")],owner).length,3752);
const appended=projectEndpoints(catalogue,[makeEvent("11","targhetti.endpoints",addition)],owner);
assert.equal(appended.length,3754);assert.equal(appended.find(e=>e.id===addition.endpoints[0].id)!.confirmedPosition,"PP3 J1-J2");
assert.equal(projectEndpoints(catalogue,[makeEvent("11","targhetti.endpoints",addition),makeEvent("12","targhetti.endpoints",manualConnection(catalogue,rows,input,"duplicate-pending"))],owner).length,3754);
assert.equal(labelRows(appended.filter(e=>e.id.startsWith("PDF:fixture:")),"both").internal[0],"PDF TEST 001 - PP3 J1-J2");
assert(equipmentGroups(rows,catalogue.pages).some(g=>g.code==="461001010001"&&g.count===0));

async function busTests() {
  let inserted: CoreEvent | undefined, transitioned=false;
  const transport: EventTransport={owner:async()=>owner,insert:async event=>{inserted={...event,id:"test",created_at:"2026-10-06",validated_at:null,validated_by:null} as CoreEvent;return inserted;},get:async()=>inserted!,transition:async()=>{transitioned=true;return inserted!;}};
  const bus=createEventBus(transport);
  await bus.propose("targhetti.positions",async()=>({catalogueId:catalogue.id,changes:[change],owner_id:"forged"}));
  assert.equal(inserted!.validation_status,"pending");assert.equal(asRecord(inserted!.payload).owner_id,owner);assert(!transitioned);
  await bus.decide("test","validated");assert(transitioned);
  inserted!.validation_status="validated";await assert.rejects(()=>bus.decide("test","validated"),/déjà traité/);
  inserted!.validation_status="pending";inserted!.payload={owner_id:"other"};await assert.rejects(()=>bus.decide("test","validated"),/inaccessible/);
  await assert.rejects(()=>bus.propose("inca.write",async()=>({})),/non pris en charge/);
  console.log("TARGHETTI : 56 pages conservées, 1876 câbles / 870 appareils retenus, 162 câbles avec * exclus, XLSX complet et deux feuilles, provenance, validation et impression OK.");
}
void busTests().catch(error=>{console.error(error);process.exitCode=1;});
