import assert from "node:assert/strict";
import { projectAutomaticPositions, validateResolutionPacket, SDC_AUTOMATIC_POLICY, type ResolutionPacket } from "../src/modules/targhetti/targhetti.resolution";
import type { EndpointState, TarghettiCatalogue } from "../src/modules/targhetti/targhetti.types";

const box = { x: 10, y: 10, width: 20, height: 10 };
const row: EndpointState = { id: "e1", equipmentCode: "411005010001", description: "", local: "", cableMark: "C RC 002", cableType: "", otherEquipmentCode: "411005010002", otherLocal: "", side: "partenza", sourceRow: 1, sourceSheet: "DATI", details: {}, candidates: [], confirmedPosition: null, confirmedPage: null, printedInternal: false, printedMetal: false };
const catalogue: TarghettiCatalogue = { schema: "core.targhetti.v1", id: "test", createdAt: "2026-10-06T00:00:00Z", excel: { name: "test.xlsx", sha256: "a".repeat(64), size: 1 }, pdf: { name: "source.pdf", sha256: SDC_AUTOMATIC_POLICY.documentSha256, size: 1 }, pages: [{ number: 1, width: 100, height: 100, text: "C RC 002 411005010001 J2 TBD", title: "", annex: null, revision: null, words: [], equipmentCodes: [row.equipmentCode], cableMarks: [row.cableMark] }], endpoints: [row], issues: [] };
const makePacket = (): ResolutionPacket => ({ schema: "core.targhetti.resolution.v1", ...SDC_AUTOMATIC_POLICY, resolutions: [{ endpointId: row.id, cableMark: row.cableMark, equipmentCode: row.equipmentCode, position: "J2", status: "resolved", evidence: [{ page: 1, cable: { text: row.cableMark, box }, equipment: { text: row.equipmentCode, box }, port: { text: "J2", box }, path: { method: "vector-terminal-frame-v1", points: [{ x: 10, y: 10 }, { x: 20, y: 10 }] } }] }] });
const project = (packet: ResolutionPacket, rows = [row]) => projectAutomaticPositions(rows, packet, catalogue, SDC_AUTOMATIC_POLICY);
assert.equal(project(makePacket())[0].confirmedPosition, "J2");
assert.equal(project(makePacket())[0].decisionMode, "automatic");
assert.equal(project(makePacket(), [{ ...row, confirmedPosition: "J9", confirmedPage: 1 }])[0].confirmedPosition, "J9");
const absent = makePacket(); absent.resolutions[0] = { ...absent.resolutions[0], status: "unresolved", position: null, evidence: [] };
assert.equal(project(absent)[0].confirmedPosition, null);
assert.equal(project(absent)[0].explicitSourceTBD, false);
const explicit = makePacket(); explicit.resolutions[0].status = "explicit_source_tbd"; explicit.resolutions[0].position = "TBD"; explicit.resolutions[0].evidence[0].port!.text = "TBD";
assert.equal(project(explicit)[0].confirmedPosition, "TBD");
assert.equal(project(explicit)[0].explicitSourceTBD, true);
const invented = makePacket(); invented.resolutions[0].position = "TBD";
assert.throws(() => project(invented));
assert.throws(() => project({ ...makePacket(), documentSha256: "b".repeat(64) }));
assert.throws(() => validateResolutionPacket({ ...makePacket(), resolutions: [] }, catalogue, SDC_AUTOMATIC_POLICY));
const uncertain = makePacket(); uncertain.resolutions[0].status = "ambiguous";
assert.throws(() => project(uncertain));
const wrongEquipment = makePacket(); wrongEquipment.resolutions[0].evidence[0].equipment.text = "411005010099";
assert.throws(() => project(wrongEquipment));
const invalidGeometry = makePacket(); invalidGeometry.resolutions[0].evidence[0].path.points[0].x = 101;
assert.throws(() => project(invalidGeometry));
const descriptionCatalogue = { ...catalogue, endpoints: [{ ...row, description: "324CSDB1-6" }] };
const descriptionMatch = makePacket(); descriptionMatch.resolutions[0].evidence[0].equipment = { text: "324CSDB1-6", box }; descriptionMatch.resolutions[0].evidence[0].equipmentMatch = "catalogue_description";
descriptionMatch.resolutions[0].evidence[0].path.method = "power-terminal-path-v1";
assert.doesNotThrow(() => validateResolutionPacket(descriptionMatch, descriptionCatalogue, SDC_AUTOMATIC_POLICY));
descriptionMatch.resolutions[0].evidence[0].equipment.text = "324CSDB1-7";
assert.throws(() => validateResolutionPacket(descriptionMatch, descriptionCatalogue, SDC_AUTOMATIC_POLICY));
const alias = makePacket(); alias.resolutions[0].evidence[0].equipment.text = "EXTENDER SMS #1"; alias.resolutions[0].evidence[0].equipmentMatch = "approved_alias";
assert.throws(() => project(alias));
const aliasPolicy = { ...SDC_AUTOMATIC_POLICY, equipmentAliases: { [row.equipmentCode]: ["EXTENDER SMS #1"] } };
assert.doesNotThrow(() => validateResolutionPacket(alias, catalogue, aliasPolicy));
alias.resolutions[0].evidence[0].equipment.text = "EXTENDER SMS #2";
assert.throws(() => validateResolutionPacket(alias, catalogue, aliasPolicy));
const direct = makePacket(); direct.resolutions[0].status = "direct"; direct.resolutions[0].position = null;
const directEvidence = direct.resolutions[0].evidence[0]; directEvidence.port = null; directEvidence.path.method = "vector-direct-terminal-v1"; directEvidence.equipmentFrame = { x: 10, y: 10, width: 50, height: 50 }; directEvidence.contact = { x: 10, y: 10 }; directEvidence.unlabelledTerminal = true;
assert.equal(project(direct)[0].internalDirect, true);
assert.equal(project(direct)[0].confirmedPosition, null);
assert.equal(project(direct)[0].confirmedPage, 1);
assert.equal(project(direct)[0].explicitSourceTBD, false);
const missingProof = structuredClone(direct); missingProof.resolutions[0].evidence = [];
assert.throws(() => project(missingProof));
const wrongContact = structuredClone(direct); wrongContact.resolutions[0].evidence[0].contact = { x: 35, y: 35 };
assert.throws(() => project(wrongContact));
const wrongFrame = structuredClone(direct); wrongFrame.resolutions[0].evidence[0].equipmentFrame = { x: 40, y: 40, width: 40, height: 40 };
assert.throws(() => project(wrongFrame));
assert.equal(project(direct, [{ ...row, confirmedPosition: "J9" }])[0].internalDirect, false);
console.log("TARGHETTI resolution tests passed.");
